name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v4
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: creates output
        run: sh ./build.sh
      - name: Push output folder to another repo with history
        run: |
          git config --global user.email "${{ secrets.ONLY1KSY_ACCOUNT_EMAIL }}"
          git config --global user.name "only1Ksy"
          git remote add deploy https://x-access-token:${{ secrets.ONLY1KSY_GITHUB_KEY }}@github.com/only1Ksy/Sanjijikfarm-Frontend.git
          git push deploy `git subtree split --prefix output main`:main --force
